name: Deploy Container to AWS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 # Updated to match your infrastructure region

      - name: Build and push Docker image
        run: |
          cd app
          docker build -t web-app:latest .

      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          echo "Deploying to EC2 instance at $EC2_PUBLIC_IP"
          # For a real deployment, you would need to set up SSH keys in GitHub secrets
          # and use them to connect to your EC2 instance
          echo "This would connect to your EC2 instance and run Docker commands"
          echo "In a production setup, you would typically use AWS SSM or SSH to execute:"
          echo "  - docker pull your-container-image"
          echo "  - docker stop existing-container"
          echo "  - docker run new-container"
